# https://github.com/ctaggart/golang-vscode
# https://travis-ci.org/ctaggart/golang-vscode

# Ubuntu Trusty 14.04 with Docker
# https://docs.travis-ci.com/user/ci-environment/
# https://docs.travis-ci.com/user/docker/
sudo: required
dist: trusty
services:
  - docker

env:
  global:
    - VERSION=0.0.0
    - if [ ! -z "$TRAVIS_TAG" ]; then VERSION=$TRAVIS_TAG; fi
    # travis encrypt DOCKER_HUB_EMAIL=a DOCKER_HUB_USERNAME=b DOCKER_HUB_PASSWORD=c
    - secure: "HnRNmXkL4XrMqq89oKn1rFaGUVC/S2okeauHwVRLY2Hc+lBTKBqk39AytAD3OjpoV1a5hklEzY9PpB/ZKsIdL0YW9DNEhLOi3vkawLj12CV+asvA/Kb++M8PmCLmaFK+XlfEHiZ7R3joDJEdJOsBEGFgRSAMydJ+N4tr/0PBguu86h2+3a5Rw5VHJTKCOyKagBAHMJSndG4Dj/Rh9+/I0O/KjOnAypZX2nuKoNevGP2x2tB4uNCOC980BvTwY/kzagEYmfQP7oEs2U0Ya6rFZr12nBKZGAFqZhUvdb7/ZYY1WS2WfxhDvT7binlnDbUvyDqK/UIfy0ebmGgvH46hWnFtX8fypowJnGXiideGcKpVldApEAyW4M5q6TwEMI8Ttdnn3VvxpJTYnP0Kmr/kzjLnrdAgN1VZ1gWzfnHHo4zsx/tp7np5GI/TLV3gaKVGUAoLvS5sIWSwwhQ3EwsquJYKUojB8pqDhhvz0WjDAdhDCWgMn3VcIHNaidMwpoVvkBW5G88Cd5MHKg6FEMk2rVoXpH3/hVfo4cEW30Y46Uy4Sq8xi5/0i9v+IQTS93zTNTMn21PYcHSNm8cyyAUQO91OGJ4tL60a3ydTtC/4InRILBBGN1UK26FZLTAj17PxAW3WWQOEDuAd2F1qZmJRqoSSq4fcDdydddLbYun+Uqw="

install: true

script:
  - docker build -t ctaggart/golang-vscode:$VERSION .

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD;
      docker push ctaggart/golang-vscode:$VERSION;
      docker tag -f ctaggart/golang-vscode:$VERSION ctaggart/golang-vscode:latest;
      docker push ctaggart/golang-vscode:latest;
    fi
